[package]
name = "nesrust"
version = "0.1.0"
authors = ["Edson Siqueira <edson.siqueira@esrlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.0"
